In [2]:
import pandas as pd
import numpy as np

In [3]:
import os

In [4]:
os.getcwd()

'C:\\Users\\Ranit\\Analytics Vidya Healthcare Analytics'

In [7]:
os.chdir("D:\\Analytics Vidya\\Healthcare Analytics")

In [9]:
os.getcwd()

'D:\\Analytics Vidya\\Healthcare Analytics'

In [10]:
train=pd.read_csv("train.csv")

In [12]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 318438 entries, 0 to 318437
Data columns (total 18 columns):
case_id                              318438 non-null int64
Hospital_code                        318438 non-null int64
Hospital_type_code                   318438 non-null object
City_Code_Hospital                   318438 non-null int64
Hospital_region_code                 318438 non-null object
Available Extra Rooms in Hospital    318438 non-null int64
Department                           318438 non-null object
Ward_Type                            318438 non-null object
Ward_Facility_Code                   318438 non-null object
Bed Grade                            318325 non-null float64
patientid                            318438 non-null int64
City_Code_Patient                    313906 non-null float64
Type of Admission                    318438 non-null object
Severity of Illness                  318438 non-null object
Visitors with Patient                318438 non-null int64
Age                                  318438 non-null object
Admission_Deposit                    318438 non-null float64
Stay                                 318438 non-null object
dtypes: float64(3), int64(6), object(9)
memory usage: 43.7+ MB

In [13]:
train.describe()

,case_id,Hospital_code,City_Code_Hospital,Available Extra Rooms in Hospital,Bed Grade,patientid,City_Code_Patient,Visitors with Patient,Admission_Deposit
count,318438.000000,318438.000000,318438.000000,318438.000000,318325.000000,318438.000000,313906.000000,318438.000000,318438.000000
mean,159219.500000,18.318841,4.771717,3.197627,2.625807,65747.579472,7.251859,3.284099,4880.749392
std,91925.276847,8.633755,3.102535,1.168171,0.873146,37979.936440,4.745266,1.764061,1086.776254
min,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1800.000000
25%,79610.250000,11.000000,2.000000,2.000000,2.000000,32847.000000,4.000000,2.000000,4186.000000
50%,159219.500000,19.000000,5.000000,3.000000,3.000000,65724.500000,8.000000,3.000000,4741.000000
75%,238828.750000,26.000000,7.000000,4.000000,3.000000,98470.000000,8.000000,4.000000,5409.000000
max,318438.000000,32.000000,13.000000,24.000000,4.000000,131624.000000,38.000000,32.000000,11008.000000

In [18]:
train.isnull().sum()

case_id                                 0
Hospital_code                           0
Hospital_type_code                      0
City_Code_Hospital                      0
Hospital_region_code                    0
Available Extra Rooms in Hospital       0
Department                              0
Ward_Type                               0
Ward_Facility_Code                      0
Bed Grade                             113
patientid                               0
City_Code_Patient                    4532
Type of Admission                       0
Severity of Illness                     0
Visitors with Patient                   0
Age                                     0
Admission_Deposit                       0
Stay                                    0
dtype: int64

In [20]:
test=pd.read_csv("test.csv")

In [22]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 137057 entries, 0 to 137056
Data columns (total 17 columns):
case_id                              137057 non-null int64
Hospital_code                        137057 non-null int64
Hospital_type_code                   137057 non-null object
City_Code_Hospital                   137057 non-null int64
Hospital_region_code                 137057 non-null object
Available Extra Rooms in Hospital    137057 non-null int64
Department                           137057 non-null object
Ward_Type                            137057 non-null object
Ward_Facility_Code                   137057 non-null object
Bed Grade                            137022 non-null float64
patientid                            137057 non-null int64
City_Code_Patient                    134900 non-null float64
Type of Admission                    137057 non-null object
Severity of Illness                  137057 non-null object
Visitors with Patient                137057 non-null int64
Age                                  137057 non-null object
Admission_Deposit                    137057 non-null float64
dtypes: float64(3), int64(6), object(8)
memory usage: 17.8+ MB

In [23]:
test.describe()

,case_id,Hospital_code,City_Code_Hospital,Available Extra Rooms in Hospital,Bed Grade,patientid,City_Code_Patient,Visitors with Patient,Admission_Deposit
count,137057.000000,137057.000000,137057.000000,137057.000000,137022.000000,137057.000000,134900.000000,137057.000000,137057.000000
mean,386967.000000,18.343747,4.758692,3.192686,2.634489,65877.903515,7.243996,3.284531,4869.731097
std,39565.092259,8.634694,3.102245,1.164250,0.869295,37942.997623,4.790625,1.777270,1080.766723
min,318439.000000,1.000000,1.000000,0.000000,1.000000,3.000000,1.000000,0.000000,1800.000000
25%,352703.000000,11.000000,2.000000,2.000000,2.000000,32945.000000,4.000000,2.000000,4178.000000
50%,386967.000000,19.000000,5.000000,3.000000,3.000000,65786.000000,8.000000,3.000000,4731.000000
75%,421231.000000,26.000000,7.000000,4.000000,3.000000,98851.000000,8.000000,4.000000,5398.000000
max,455495.000000,32.000000,13.000000,21.000000,4.000000,131618.000000,38.000000,32.000000,11920.000000

In [25]:
test.isnull().sum()

case_id                                 0
Hospital_code                           0
Hospital_type_code                      0
City_Code_Hospital                      0
Hospital_region_code                    0
Available Extra Rooms in Hospital       0
Department                              0
Ward_Type                               0
Ward_Facility_Code                      0
Bed Grade                              35
patientid                               0
City_Code_Patient                    2157
Type of Admission                       0
Severity of Illness                     0
Visitors with Patient                   0
Age                                     0
Admission_Deposit                       0
dtype: int64

In [26]:
train.isnull().sum()

case_id                                 0
Hospital_code                           0
Hospital_type_code                      0
City_Code_Hospital                      0
Hospital_region_code                    0
Available Extra Rooms in Hospital       0
Department                              0
Ward_Type                               0
Ward_Facility_Code                      0
Bed Grade                             113
patientid                               0
City_Code_Patient                    4532
Type of Admission                       0
Severity of Illness                     0
Visitors with Patient                   0
Age                                     0
Admission_Deposit                       0
Stay                                    0
dtype: int64

In [28]:
train.shape

(318438, 18)

In [30]:
test.shape

(137057, 17)

In [33]:
train.columns

Index(['case_id', 'Hospital_code', 'Hospital_type_code', 'City_Code_Hospital',
       'Hospital_region_code', 'Available Extra Rooms in Hospital',
       'Department', 'Ward_Type', 'Ward_Facility_Code', 'Bed Grade',
       'patientid', 'City_Code_Patient', 'Type of Admission',
       'Severity of Illness', 'Visitors with Patient', 'Age',
       'Admission_Deposit', 'Stay'],
      dtype='object')

In [35]:
test.columns

Index(['case_id', 'Hospital_code', 'Hospital_type_code', 'City_Code_Hospital',
       'Hospital_region_code', 'Available Extra Rooms in Hospital',
       'Department', 'Ward_Type', 'Ward_Facility_Code', 'Bed Grade',
       'patientid', 'City_Code_Patient', 'Type of Admission',
       'Severity of Illness', 'Visitors with Patient', 'Age',
       'Admission_Deposit'],
      dtype='object')

In [39]:
train_df=train.drop(['Stay'],axis=1)

In [42]:
train_df.columns

Index(['case_id', 'Hospital_code', 'Hospital_type_code', 'City_Code_Hospital',
       'Hospital_region_code', 'Available Extra Rooms in Hospital',
       'Department', 'Ward_Type', 'Ward_Facility_Code', 'Bed Grade',
       'patientid', 'City_Code_Patient', 'Type of Admission',
       'Severity of Illness', 'Visitors with Patient', 'Age',
       'Admission_Deposit'],
      dtype='object')

In [46]:
train_df['flag']=1

In [49]:
train_df.head(2)

,case_id,Hospital_code,Hospital_type_code,City_Code_Hospital,Hospital_region_code,Available Extra Rooms in Hospital,Department,Ward_Type,Ward_Facility_Code,Bed Grade,patientid,City_Code_Patient,Type of Admission,Severity of Illness,Visitors with Patient,Age,Admission_Deposit,flag
0,1,8,c,3,Z,3,radiotherapy,R,F,2.0,31397,7.0,Emergency,Extreme,2,51-60,4911.0,1
1,2,2,c,5,Z,2,radiotherapy,S,F,2.0,31397,7.0,Trauma,Extreme,2,51-60,5954.0,1

In [51]:
test_df=test

In [53]:
test_df['flag']=0

In [55]:
test_df.head(2)

,case_id,Hospital_code,Hospital_type_code,City_Code_Hospital,Hospital_region_code,Available Extra Rooms in Hospital,Department,Ward_Type,Ward_Facility_Code,Bed Grade,patientid,City_Code_Patient,Type of Admission,Severity of Illness,Visitors with Patient,Age,Admission_Deposit,flag
0,318439,21,c,3,Z,3,gynecology,S,A,2.0,17006,2.0,Emergency,Moderate,2,71-80,3095.0,0
1,318440,29,a,4,X,2,gynecology,S,F,2.0,17006,2.0,Trauma,Moderate,4,71-80,4018.0,0

In [79]:
clean=pd.concat([train_df,test_df])

In [80]:
clean

,case_id,Hospital_code,Hospital_type_code,City_Code_Hospital,Hospital_region_code,Available Extra Rooms in Hospital,Department,Ward_Type,Ward_Facility_Code,Bed Grade,patientid,City_Code_Patient,Type of Admission,Severity of Illness,Visitors with Patient,Age,Admission_Deposit,flag
0,1,8,c,3,Z,3,radiotherapy,R,F,2.0,31397,7.0,Emergency,Extreme,2,51-60,4911.0,1
1,2,2,c,5,Z,2,radiotherapy,S,F,2.0,31397,7.0,Trauma,Extreme,2,51-60,5954.0,1
2,3,10,e,1,X,2,anesthesia,S,E,2.0,31397,7.0,Trauma,Extreme,2,51-60,4745.0,1
3,4,26,b,2,Y,2,radiotherapy,R,D,2.0,31397,7.0,Trauma,Extreme,2,51-60,7272.0,1
4,5,26,b,2,Y,2,radiotherapy,S,D,2.0,31397,7.0,Trauma,Extreme,2,51-60,5558.0,1
5,6,23,a,6,X,2,anesthesia,S,F,2.0,31397,7.0,Trauma,Extreme,2,51-60,4449.0,1
6,7,32,f,9,Y,1,radiotherapy,S,B,3.0,31397,7.0,Emergency,Extreme,2,51-60,6167.0,1
7,8,23,a,6,X,4,radiotherapy,Q,F,3.0,31397,7.0,Trauma,Extreme,2,51-60,5571.0,1
8,9,1,d,10,Y,2,gynecology,R,B,4.0,31397,7.0,Trauma,Extreme,2,51-60,7223.0,1
9,10,10,e,1,X,2,gynecology,S,E,3.0,31397,7.0,Trauma,Extreme,2,51-60,6056.0,1
10,11,22,g,9,Y,2,radiotherapy,S,B,2.0,31397,7.0,Urgent,Extreme,2,51-60,5797.0,1
11,12,26,b,2,Y,4,radiotherapy,R,D,1.0,31397,7.0,Urgent,Extreme,2,51-60,5993.0,1
12,13,16,c,3,Z,2,radiotherapy,R,A,3.0,31397,7.0,Emergency,Extreme,2,51-60,5141.0,1
13,14,9,d,5,Z,3,radiotherapy,S,F,3.0,31397,7.0,Urgent,Extreme,2,51-60,8477.0,1
14,15,6,a,6,X,4,gynecology,Q,F,3.0,63418,8.0,Emergency,Extreme,2,71-80,2685.0,1
15,16,6,a,6,X,3,gynecology,Q,F,3.0,63418,8.0,Emergency,Extreme,2,71-80,9398.0,1
16,17,23,a,6,X,4,radiotherapy,Q,F,3.0,63418,8.0,Urgent,Extreme,4,71-80,2933.0,1
17,18,29,a,4,X,4,anesthesia,S,F,3.0,63418,8.0,Emergency,Extreme,2,71-80,5342.0,1
18,19,32,f,9,Y,4,radiotherapy,S,B,2.0,63418,8.0,Trauma,Extreme,2,71-80,7442.0,1
19,20,12,a,9,Y,4,radiotherapy,Q,B,2.0,63418,8.0,Trauma,Extreme,2,71-80,5155.0,1
20,21,16,c,3,Z,2,anesthesia,S,A,3.0,63418,8.0,Trauma,Extreme,2,71-80,8181.0,1
21,22,3,c,3,Z,2,anesthesia,R,A,3.0,63418,8.0,Trauma,Extreme,2,71-80,6672.0,1
22,23,21,c,3,Z,2,anesthesia,S,A,3.0,63418,8.0,Trauma,Extreme,2,71-80,6364.0,1
23,24,6,a,6,X,3,anesthesia,R,F,3.0,63418,8.0,Urgent,Extreme,2,71-80,4664.0,1
24,25,26,b,2,Y,4,radiotherapy,Q,D,1.0,63418,8.0,Trauma,Extreme,4,71-80,4091.0,1
25,26,28,b,11,X,4,gynecology,R,F,2.0,8088,2.0,Emergency,Moderate,2,31-40,2405.0,1
26,27,26,b,2,Y,4,anesthesia,Q,D,3.0,8088,2.0,Trauma,Moderate,2,31-40,5164.0,1
27,28,26,b,2,Y,4,gynecology,R,D,3.0,8088,2.0,Trauma,Moderate,2,31-40,5055.0,1
28,29,6,a,6,X,4,gynecology,Q,F,2.0,8088,2.0,Trauma,Moderate,4,31-40,3339.0,1
29,30,27,a,7,Y,4,gynecology,R,C,2.0,8088,2.0,Trauma,Moderate,2,31-40,5757.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137027,455466,32,f,9,Y,3,gynecology,S,B,2.0,15179,8.0,Urgent,Moderate,2,41-50,4397.0,0
137028,455467,19,a,7,Y,3,gynecology,Q,C,3.0,84978,8.0,Emergency,Moderate,5,51-60,3906.0,0
137029,455468,15,c,5,Z,2,radiotherapy,R,F,4.0,43022,7.0,Urgent,Minor,2,11-20,8316.0,0
137030,455469,9,d,5,Z,3,gynecology,R,F,4.0,67792,5.0,Urgent,Moderate,2,11-20,3815.0,0
137031,455470,25,e,1,X,4,gynecology,R,E,4.0,45954,10.0,Trauma,Minor,5,61-70,4050.0,0
137032,455471,27,a,7,Y,6,gynecology,Q,C,4.0,40918,8.0,Trauma,Minor,3,21-30,3017.0,0
137033,455472,12,a,9,Y,4,gynecology,S,B,2.0,90642,7.0,Urgent,Minor,4,71-80,4365.0,0
137034,455473,17,e,1,X,2,anesthesia,R,E,4.0,68012,18.0,Urgent,Minor,2,61-70,4587.0,0
137035,455474,16,c,3,Z,2,gynecology,S,A,4.0,1617,4.0,Emergency,Minor,3,31-40,8933.0,0
137036,455475,23,a,6,X,4,anesthesia,Q,F,4.0,109822,5.0,Trauma,Moderate,4,41-50,5760.0,0
137037,455476,23,a,6,X,4,gynecology,R,F,4.0,101360,2.0,Emergency,Minor,6,0-10,3020.0,0
137038,455477,6,a,6,X,4,gynecology,R,F,4.0,101360,2.0,Emergency,Minor,6,0-10,3858.0,0
137039,455478,19,a,7,Y,5,gynecology,Q,C,2.0,41025,8.0,Emergency,Moderate,4,71-80,3862.0,0
137040,455479,24,a,1,X,2,TB & Chest disease,R,E,4.0,75048,10.0,Trauma,Minor,3,41-50,4749.0,0
137041,455480,19,a,7,Y,2,gynecology,S,C,2.0,124764,8.0,Emergency,Minor,4,51-60,2804.0,0
137042,455481,11,b,2,Y,3,gynecology,Q,D,3.0,84400,18.0,Urgent,Extreme,3,51-60,5577.0,0
137043,455482,15,c,5,Z,5,gynecology,Q,F,4.0,93774,21.0,Emergency,Moderate,4,71-80,5675.0,0
137044,455483,15,c,5,Z,2,gynecology,R,F,4.0,14503,8.0,Trauma,Moderate,2,51-60,5416.0,0
137045,455484,19,a,7,Y,3,gynecology,Q,C,3.0,15705,8.0,Emergency,Minor,3,51-60,3641.0,0
137046,455485,14,a,1,X,2,anesthesia,Q,E,4.0,35621,10.0,Urgent,Minor,2,0-10,4800.0,0
137047,455486,9,d,5,Z,2,gynecology,S,F,4.0,55235,4.0,Emergency,Moderate,3,31-40,4418.0,0
137048,455487,13,a,5,Z,2,gynecology,R,F,3.0,55235,4.0,Emergency,Moderate,2,31-40,3816.0,0
137049,455488,12,a,9,Y,6,gynecology,Q,B,2.0,99515,7.0,Emergency,Moderate,4,61-70,4406.0,0
137050,455489,13,a,5,Z,3,gynecology,R,F,3.0,22878,21.0,Emergency,Moderate,3,21-30,4573.0,0
137051,455490,15,c,5,Z,2,gynecology,S,F,4.0,118215,6.0,Urgent,Minor,2,21-30,5241.0,0
137052,455491,11,b,2,Y,4,anesthesia,Q,D,3.0,41160,3.0,Emergency,Minor,4,41-50,6313.0,0
137053,455492,25,e,1,X,2,radiotherapy,R,E,4.0,30985,7.0,Emergency,Moderate,2,0-10,3510.0,0
137054,455493,30,c,3,Z,2,anesthesia,R,A,4.0,81811,12.0,Urgent,Minor,2,0-10,7190.0,0
137055,455494,5,a,1,X,2,anesthesia,R,E,4.0,57021,10.0,Trauma,Minor,2,41-50,5435.0,0
137056,455495,6,a,6,X,3,gynecology,Q,F,4.0,126729,3.0,Trauma,Extreme,5,51-60,4702.0,0

In [81]:
clean.columns

Index(['case_id', 'Hospital_code', 'Hospital_type_code', 'City_Code_Hospital',
       'Hospital_region_code', 'Available Extra Rooms in Hospital',
       'Department', 'Ward_Type', 'Ward_Facility_Code', 'Bed Grade',
       'patientid', 'City_Code_Patient', 'Type of Admission',
       'Severity of Illness', 'Visitors with Patient', 'Age',
       'Admission_Deposit', 'flag'],
      dtype='object')

In [82]:
clean.drop(['case_id'],axis=1,inplace=True)

In [84]:
clean.columns

Index(['Hospital_code', 'Hospital_type_code', 'City_Code_Hospital',
       'Hospital_region_code', 'Available Extra Rooms in Hospital',
       'Department', 'Ward_Type', 'Ward_Facility_Code', 'Bed Grade',
       'patientid', 'City_Code_Patient', 'Type of Admission',
       'Severity of Illness', 'Visitors with Patient', 'Age',
       'Admission_Deposit', 'flag'],
      dtype='object')

In [86]:
clean.drop(['patientid'],axis=1,inplace=True)

KeyError: "['patientid'] not found in axis"

In [88]:
clean.columns

Index(['Hospital_code', 'Hospital_type_code', 'City_Code_Hospital',
       'Hospital_region_code', 'Available Extra Rooms in Hospital',
       'Department', 'Ward_Type', 'Ward_Facility_Code', 'Bed Grade',
       'City_Code_Patient', 'Type of Admission', 'Severity of Illness',
       'Visitors with Patient', 'Age', 'Admission_Deposit', 'flag'],
      dtype='object')

In [90]:
clean.shape

(455495, 16)

In [92]:
clean.isnull().sum()

Hospital_code                           0
Hospital_type_code                      0
City_Code_Hospital                      0
Hospital_region_code                    0
Available Extra Rooms in Hospital       0
Department                              0
Ward_Type                               0
Ward_Facility_Code                      0
Bed Grade                             148
City_Code_Patient                    6689
Type of Admission                       0
Severity of Illness                     0
Visitors with Patient                   0
Age                                     0
Admission_Deposit                       0
flag                                    0
dtype: int64

In [97]:
for column in ['Bed Grade','City_Code_Patient' ]:
    clean[column].fillna(clean[column].mode()[0], inplace=True)

In [99]:
clean.isnull().sum()

Hospital_code                        0
Hospital_type_code                   0
City_Code_Hospital                   0
Hospital_region_code                 0
Available Extra Rooms in Hospital    0
Department                           0
Ward_Type                            0
Ward_Facility_Code                   0
Bed Grade                            0
City_Code_Patient                    0
Type of Admission                    0
Severity of Illness                  0
Visitors with Patient                0
Age                                  0
Admission_Deposit                    0
flag                                 0
dtype: int64

In [267]:
clean.columns

Index(['Hospital_code', 'Hospital_type_code', 'City_Code_Hospital',
       'Hospital_region_code', 'Available Extra Rooms in Hospital',
       'Department', 'Ward_Type', 'Ward_Facility_Code', 'Bed Grade',
       'City_Code_Patient', 'Type of Admission', 'Severity of Illness',
       'Visitors with Patient', 'Age', 'Admission_Deposit', 'flag'],
      dtype='object')

In [319]:
train_set=clean.loc[clean['flag']==1]

In [320]:
train_set.shape

(318438, 16)

In [321]:
test_set=clean.loc[clean['flag']==0]

In [322]:
test_set.shape

(137057, 16)

In [323]:
train_set.columns

Index(['Hospital_code', 'Hospital_type_code', 'City_Code_Hospital',
       'Hospital_region_code', 'Available Extra Rooms in Hospital',
       'Department', 'Ward_Type', 'Ward_Facility_Code', 'Bed Grade',
       'City_Code_Patient', 'Type of Admission', 'Severity of Illness',
       'Visitors with Patient', 'Age', 'Admission_Deposit', 'flag'],
      dtype='object')

In [324]:
train_set.shape

(318438, 16)

In [325]:
train_set.drop('flag',axis=1,inplace=True)

In [326]:
train_set.shape

(318438, 15)

In [327]:
test_set.shape

(137057, 16)

In [328]:
test_set.columns

Index(['Hospital_code', 'Hospital_type_code', 'City_Code_Hospital',
       'Hospital_region_code', 'Available Extra Rooms in Hospital',
       'Department', 'Ward_Type', 'Ward_Facility_Code', 'Bed Grade',
       'City_Code_Patient', 'Type of Admission', 'Severity of Illness',
       'Visitors with Patient', 'Age', 'Admission_Deposit', 'flag'],
      dtype='object')

In [329]:
test_set.drop('flag',axis=1,inplace=True)

In [331]:
train_set.head(2)

,Hospital_code,Hospital_type_code,City_Code_Hospital,Hospital_region_code,Available Extra Rooms in Hospital,Department,Ward_Type,Ward_Facility_Code,Bed Grade,City_Code_Patient,Type of Admission,Severity of Illness,Visitors with Patient,Age,Admission_Deposit
0,8,c,3,Z,3,radiotherapy,R,F,2.0,7.0,Emergency,Extreme,2,51-60,4911.0
1,2,c,5,Z,2,radiotherapy,S,F,2.0,7.0,Trauma,Extreme,2,51-60,5954.0

In [332]:
train_set['Hospital_code'] = train_set['Hospital_code'].astype('category')
train_set['Hospital_type_code'] = train_set['Hospital_type_code'].astype('category')
train_set['City_Code_Hospital'] = train_set['City_Code_Hospital'].astype('category')
train_set['Hospital_region_code'] = train_set['Hospital_region_code'].astype('category')
train_set['Department'] = train_set['Department'].astype('category')
train_set['Ward_Type'] = train_set['Ward_Type'].astype('category')
train_set['Ward_Facility_Code'] = train_set['Ward_Facility_Code'].astype('category')
train_set['Bed Grade'] = train_set['Bed Grade'].astype('category')
train_set['City_Code_Patient'] = train_set['City_Code_Patient'].astype('category')
train_set['Type of Admission'] = train_set['Type of Admission'].astype('category')
train_set['Severity of Illness'] = train_set['Severity of Illness'].astype('category')
train_set['Age'] = train_set['Age'].astype('category')

C:\Users\Ranit\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\Ranit\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Ranit\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Ranit\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\Ranit\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\Ranit\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Ranit\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
C:\Users\Ranit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Ranit\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
C:\Users\Ranit\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Ranit\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\Ranit\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':

In [310]:
from sklearn.preprocessing import LabelEncoder

In [311]:
le = LabelEncoder()

In [333]:
train_set= pd.get_dummies(train_set)

In [334]:
train_set.columns

Index(['Available Extra Rooms in Hospital', 'Visitors with Patient',
       'Admission_Deposit', 'Hospital_code_1', 'Hospital_code_2',
       'Hospital_code_3', 'Hospital_code_4', 'Hospital_code_5',
       'Hospital_code_6', 'Hospital_code_7',
       ...
       'Age_0-10', 'Age_11-20', 'Age_21-30', 'Age_31-40', 'Age_41-50',
       'Age_51-60', 'Age_61-70', 'Age_71-80', 'Age_81-90', 'Age_91-100'],
      dtype='object', length=130)

In [335]:
train_set.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 318438 entries, 0 to 318437
Columns: 130 entries, Available Extra Rooms in Hospital to Age_91-100
dtypes: float64(1), int64(2), uint8(127)
memory usage: 48.3 MB

In [338]:
train_set.shape

(318438, 130)

In [341]:
train_set.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 318438 entries, 0 to 318437
Columns: 130 entries, Available Extra Rooms in Hospital to Age_91-100
dtypes: float64(1), int64(2), uint8(127)
memory usage: 48.3 MB

In [342]:
training_set=pd.concat([train_set,train['Stay']],axis=1)

In [344]:
training_set.head(2)

,Available Extra Rooms in Hospital,Visitors with Patient,Admission_Deposit,Hospital_code_1,Hospital_code_2,Hospital_code_3,Hospital_code_4,Hospital_code_5,Hospital_code_6,Hospital_code_7,...,Age_11-20,Age_21-30,Age_31-40,Age_41-50,Age_51-60,Age_61-70,Age_71-80,Age_81-90,Age_91-100,Stay
0,3,2,4911.0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0-10
1,2,2,5954.0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,41-50

In [346]:
from sklearn.model_selection import train_test_split

In [347]:
x=training_set.loc[:, training_set.columns != 'Stay']

In [348]:
y=training_set['Stay']

In [349]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=101)

In [350]:
x_train.columns

Index(['Available Extra Rooms in Hospital', 'Visitors with Patient',
       'Admission_Deposit', 'Hospital_code_1', 'Hospital_code_2',
       'Hospital_code_3', 'Hospital_code_4', 'Hospital_code_5',
       'Hospital_code_6', 'Hospital_code_7',
       ...
       'Age_0-10', 'Age_11-20', 'Age_21-30', 'Age_31-40', 'Age_41-50',
       'Age_51-60', 'Age_61-70', 'Age_71-80', 'Age_81-90', 'Age_91-100'],
      dtype='object', length=130)

In [353]:
x_test.head(2)

,Available Extra Rooms in Hospital,Visitors with Patient,Admission_Deposit,Hospital_code_1,Hospital_code_2,Hospital_code_3,Hospital_code_4,Hospital_code_5,Hospital_code_6,Hospital_code_7,...,Age_0-10,Age_11-20,Age_21-30,Age_31-40,Age_41-50,Age_51-60,Age_61-70,Age_71-80,Age_81-90,Age_91-100
118654,2,2,4118.0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
232495,4,2,5039.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [355]:
y_train.head()

222709                  0-10
141084                 21-30
204225    More than 100 Days
108645                 21-30
110172                 31-40
Name: Stay, dtype: object

In [357]:
y_test.head()

118654     0-10
232495    11-20
62794     51-60
293391    11-20
35919     21-30
Name: Stay, dtype: object

In [365]:
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from lightgbm import LGBMClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from matplotlib import pyplot

In [369]:
from sklearn.metrics import accuracy_score

In [370]:
# define dataset
#X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, random_state=1)
# evaluate the model
model = LGBMClassifier()
#cv = RepeatedStratifiedKFold(n_splits=3, n_repeats=3, random_state=1)
#n_scores = cross_val_score(model, x_train, y_train, scoring='accuracy', cv=cv, error_score='raise')
#print('Accuracy: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))
# fit the model on the whole dataset
model.fit(x_train, y_train)
# make a single prediction
predict = model.predict(x_test)
print(accuracy_score(y_test,predict))

0.4256374827283005

In [398]:
# define dataset
#X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, random_state=1)
# evaluate the model
model = LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=100, objective=None,
               random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0, max_bin= 100)

model.fit(x_train, y_train)
# make a single prediction
predict = model.predict(x_test)
print(accuracy_score(y_test,predict))

0.42785140057781684

In [424]:
# define dataset
#X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, random_state=1)
# evaluate the model
model = LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=100, objective=None,
               random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample=1.0, subsample_for_bin=300000, subsample_freq=0, max_bin= 100)

model.fit(x_train, y_train)
# make a single prediction
predict = model.predict(x_test)
print(accuracy_score(y_test,predict))

0.42829104383871375

In [431]:
import pandas as pd
import numpy as np
pred=pd.DataFrame(predict)

In [434]:
test_set.head(2)

,Hospital_code,Hospital_type_code,City_Code_Hospital,Hospital_region_code,Available Extra Rooms in Hospital,Department,Ward_Type,Ward_Facility_Code,Bed Grade,City_Code_Patient,Type of Admission,Severity of Illness,Visitors with Patient,Age,Admission_Deposit
0,21,c,3,Z,3,gynecology,S,A,2.0,2.0,Emergency,Moderate,2,71-80,3095.0
1,29,a,4,X,2,gynecology,S,F,2.0,2.0,Trauma,Moderate,4,71-80,4018.0

In [435]:
test_set['Hospital_code'] = test_set['Hospital_code'].astype('category')
test_set['Hospital_type_code'] = test_set['Hospital_type_code'].astype('category')
test_set['City_Code_Hospital'] = test_set['City_Code_Hospital'].astype('category')
test_set['Hospital_region_code'] = test_set['Hospital_region_code'].astype('category')
test_set['Department'] = test_set['Department'].astype('category')
test_set['Ward_Type'] = test_set['Ward_Type'].astype('category')
test_set['Ward_Facility_Code'] = test_set['Ward_Facility_Code'].astype('category')
test_set['Bed Grade'] = test_set['Bed Grade'].astype('category')
test_set['City_Code_Patient'] = test_set['City_Code_Patient'].astype('category')
test_set['Type of Admission'] = test_set['Type of Admission'].astype('category')
test_set['Severity of Illness'] = test_set['Severity of Illness'].astype('category')
test_set['Age'] = test_set['Age'].astype('category')

C:\Users\Ranit\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\Ranit\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Ranit\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Ranit\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\Ranit\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\Ranit\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Ranit\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
C:\Users\Ranit\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Ranit\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
C:\Users\Ranit\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Ranit\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\Ranit\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':

In [438]:
test_set1= pd.get_dummies(test_set)

In [441]:
test_set1.columns

Index(['Available Extra Rooms in Hospital', 'Visitors with Patient',
       'Admission_Deposit', 'Hospital_code_1', 'Hospital_code_2',
       'Hospital_code_3', 'Hospital_code_4', 'Hospital_code_5',
       'Hospital_code_6', 'Hospital_code_7',
       ...
       'Age_0-10', 'Age_11-20', 'Age_21-30', 'Age_31-40', 'Age_41-50',
       'Age_51-60', 'Age_61-70', 'Age_71-80', 'Age_81-90', 'Age_91-100'],
      dtype='object', length=130)

In [442]:
pred= model.predict(test_set1)

In [444]:
final_predictions=pd.DataFrame(pred)

In [447]:
final_predictions.columns=['Stay']

In [455]:
Submission=pd.concat((test['case_id'],final_predictions['Stay']),axis=1)

TypeError: concat() got an unexpected keyword argument 'index'

In [457]:
import os

In [458]:
os.getcwd()

'D:\\Analytics Vidya\\Healthcare Analytics'

In [460]:
Submission.to_csv("submission.csv",index=False)

Different hyper tuning parameters

In [465]:
model1 = LGBMClassifier(boosting_type='gbdt', colsample_bytree=0.8,
               learning_rate=0.04,min_child_samples=228,
               n_estimators=50000, n_jobs=-1, objective='multi_class',
               reg_alpha=1, reg_lambda=1,
               max_bin= 63,num_class=11 )

model.fit(x_train, y_train)
# make a single prediction
predict = model.predict(x_test)
print(accuracy_score(y_test,predict))

0.42829104383871375